module.exports = [
// 'computational materials science',
// 'Separated representation',
'Model reduction',
'Homogenization',
'Multiscale analysis',
'Topology optimization',
'Proper Orthogonal Decomposition',
'Diffuse Approximation',
'Parallel computing',
'Topology optimization',
'Lattice Boltzmann method',
'Lattice structure',
'Selective laser melting',
'Functionally graded',
'Energy absorption',
'Composite',
'Numerical homogenization',
'Identification',
'Evolutionary algorithm',
'Artificial immune system',
'structural engineering',
'mechanical systems',
'mechanics of materials',
'materials science',
'computational models and programs',
'computational models and programs associated with the design',
'control and analysis of experiment',
'mathematical and numerical methods and algorithms',
'algebraic computation',
'advanced computer architecture',
'special purpose computers on computing in the physical sciences',
'physical sciencest',
'ribo-surfaces',
'bio-tribology',
'surface engineering and materials',
'contact mechanics',
'nano-tribology',
'lubricants and hydrodynamic lubrication',
'computer-based engineering',
'mechanical engineering',
'aerospace engineering',
'civil engineering',
'environmental engineering',
'mathematical modeling',
'computational science and engineering',
'Innovative computational strategies and numerical algorithms for large-scale engineering problems',
'Analysis and simulation techniques and systems',
'Model and mesh generation',
'Control of the accuracy, stability and efficiency of computational process',
'Exploitation of new computing environments (eg distributed hetergeneous and collaborative computing)',
'Advanced visualization techniques, virtual environments and prototyping',
'Applications of AI, knowledge-based systems, computational intelligence, including fuzzy logic, neural networks and evolutionary computations',
'Application of object-oriented technology to engineering problems',
'Intelligent human computer interfaces',
'Design automation, multidisciplinary design and optimization',
'CAD, CAE and integrated process and product development systems',
'Quality and reliability',
'Dynamical Systems',
'Solid Mechanics',
'Fluid Mechanics',
'Acoustics',
'Wave Motion',
'Control Theory',
'Signal Processing',
]